CREATE DATABASE canvialy;

CREATE TABLE "events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(45),
  "status_id" integer,
  "start_date" timestamp,
  "end_date" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp,
  "event_types_id" integer
);

CREATE TABLE "event_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100)
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mail" varchar(100),
  "accept_terms_and_conditions" boolean,
  "allow_sending_emails" boolean,
  "instagram" varchar(45),
  "twitter" varchar(45),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "ticket_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100)
);

CREATE TABLE "event_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100)
);

CREATE TABLE "tickets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticker_status_id" integer,
  "description" varchar(100),
  "user_id" integer,
  "event_id" integer,
  "quantity" integer,
  "count" integer,
  "unit_price" "decimal(10, 2)",
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "locations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city" varchar(45),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "event_locations" (
  "event_id" integer,
  "location_id" integer
);

CREATE TABLE "feedback" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar(100),
  "ticket_id" integer,
  "created_at" timestamp,
  "updated_at" timestamp
);

ALTER TABLE "events" ADD FOREIGN KEY ("status_id") REFERENCES "event_status" ("id");

ALTER TABLE "events" ADD FOREIGN KEY ("event_types_id") REFERENCES "event_types" ("id");

ALTER TABLE "tickets" ADD FOREIGN KEY ("ticker_status_id") REFERENCES "ticket_status" ("id");

ALTER TABLE "tickets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "tickets" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id");

ALTER TABLE "event_locations" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id");

ALTER TABLE "event_locations" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("id");

ALTER TABLE "feedback" ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id");


INSERT INTO event_status values 
  (1, 'Esdeveniment publicat'),
  (2, 'Esdeveniment eliminat'),
  (3, 'Esdeveniment cancelat'),
  (4, 'Esdeveniment caducat');

INSERT INTO ticket_status values 
  (1, 'Entrada publicada'),
  (2, 'Em quedo l''entrada'),
  (3, 'Intercanviada a través de Eventickets'),
  (4, 'Intercanviada a través d''una altra APP'),
  (5, 'Intercanviada amb coneguts'),
  (6, 'Esdeveniment cancel·lat'),
  (7, 'Entrada caducada'),
  (8, 'Entrada mal publicada');